In [10]:
!pip install numpy --upgrade

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.9 MB 2.5 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.9 MB 3.0 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.9 MB 3.4 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.9 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.9 MB 4.0 MB/s eta 0:00:03
   ----------------- ---------------------- 5.8/12.9 MB 4.1 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.9 MB 4.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.9 MB 4.4 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.9 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 10.5/12.9 MB 4.7 MB/s eta 0:00:01
   ----------------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.2.6 which is incompatible.
tensorflow 2.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, but you have protobuf 6.30.2 which is incompatible.
pyarrow 15.0.0 requires numpy<2,>=1.16.6, but you have numpy 2.2.6 which is incompatible.
statsmodels 0.14.1 requires numpy<2,>=1.18, but you have numpy 2.2.6 which is incompatible.
statsmodels 0.14.1 requires numpy<2,>=1.22.3; python_version == "3.10" and platform_system == "Windows" and platform_python_implementation != "PyPy", but you have numpy 2.2.6 which is incompatible.
streamlit 1.40.2 requires protobuf<6,>=3.20, but you have protobuf 6.30.2 which is incompatible.
tensorflow-intel 2.13.1 requires keras<2.14,>=2.13.1, but you have keras 3.9.1 which is in

In [11]:
import numpy as np

In [59]:
np.arange(1,100,2).size

50

In [62]:
c=np.random.randint(size=[2,3,4],high=100,low=10)

In [34]:
a=np.array([1,2,3,4,5],dtype=np.float32)
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [35]:
a.dtype

dtype('float32')

In [39]:
b=np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [40]:
a*b

array([ 3.,  8., 15., 24., 35.])

In [41]:
a@b

np.float64(85.0)

In [45]:
a.shape

(5,)

In [54]:
len(c)

3

In [56]:
c.size

AttributeError: 'tuple' object has no attribute 'size'

In [60]:
b.size

5

In [67]:
c.astype(np.int32)

array([[[36, 38, 52, 53],
        [96, 54, 97, 44],
        [89, 29, 66, 78]],

       [[55, 75, 19, 33],
        [15, 80, 99, 86],
        [82, 96, 76, 39]]], dtype=int32)

In [76]:
np.linspace(0,2,100)

array([0.        , 0.02020202, 0.04040404, 0.06060606, 0.08080808,
       0.1010101 , 0.12121212, 0.14141414, 0.16161616, 0.18181818,
       0.2020202 , 0.22222222, 0.24242424, 0.26262626, 0.28282828,
       0.3030303 , 0.32323232, 0.34343434, 0.36363636, 0.38383838,
       0.4040404 , 0.42424242, 0.44444444, 0.46464646, 0.48484848,
       0.50505051, 0.52525253, 0.54545455, 0.56565657, 0.58585859,
       0.60606061, 0.62626263, 0.64646465, 0.66666667, 0.68686869,
       0.70707071, 0.72727273, 0.74747475, 0.76767677, 0.78787879,
       0.80808081, 0.82828283, 0.84848485, 0.86868687, 0.88888889,
       0.90909091, 0.92929293, 0.94949495, 0.96969697, 0.98989899,
       1.01010101, 1.03030303, 1.05050505, 1.07070707, 1.09090909,
       1.11111111, 1.13131313, 1.15151515, 1.17171717, 1.19191919,
       1.21212121, 1.23232323, 1.25252525, 1.27272727, 1.29292929,
       1.31313131, 1.33333333, 1.35353535, 1.37373737, 1.39393939,
       1.41414141, 1.43434343, 1.45454545, 1.47474747, 1.49494

In [72]:
np.arange(0,2,0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75])

In [80]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
w=np.full([2,3],3)

In [85]:
q=np.full([3,2],5)

In [87]:
import torch


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "c:\Users\Asus\AppData\Local\Programs\Python\Python310\lib\site-packages\traitlets

In [92]:
w=torch.tensor(w,dtype=torch.int64)
q=torch.tensor(q,dtype=torch.int64)

In [93]:
torch.matmul(w,q) 

tensor([[45, 45],
        [45, 45]])

In [104]:
np.exp(a)

array([  2.718282 ,   7.3890557,  20.085537 ,  54.59815  , 148.41316  ],
      dtype=float32)

In [105]:
np.mean(a)

np.float32(3.0)

In [106]:
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [128]:

e=np.random.normal(5,10,[4,5])
q=np.random.normal(5,10,[5,4])
np.average(e)

np.float64(8.133852412715063)

In [130]:
np.average(e@q)

np.float64(128.65644704954218)

In [131]:
e

array([[ 6.01627781, 10.06716749,  6.90978153,  5.97367407, 15.82466177],
       [14.35893047, 22.64110069, 19.0036402 , 18.86498965, -4.36074537],
       [19.85630671,  7.79235545,  6.61490195,  9.02449352, -7.82909249],
       [17.22731283, -0.54704134,  0.85300269, -3.72814844, -1.88652091]])

In [132]:
e>0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [ True, False,  True, False, False]])

In [137]:
x=e[e>0]

In [138]:
x

array([ 6.01627781, 10.06716749,  6.90978153,  5.97367407, 15.82466177,
       14.35893047, 22.64110069, 19.0036402 , 18.86498965, 19.85630671,
        7.79235545,  6.61490195,  9.02449352, 17.22731283,  0.85300269])

In [139]:
x.shape

(15,)

In [140]:
a

array([1., 2., 3., 4., 5.], dtype=float32)

In [142]:
a.shape


(5,)

In [144]:
c

array([[[36, 38, 52, 53],
        [96, 54, 97, 44],
        [89, 29, 66, 78]],

       [[55, 75, 19, 33],
        [15, 80, 99, 86],
        [82, 96, 76, 39]]], dtype=int32)

In [145]:
c.shape

(2, 3, 4)

In [153]:
c.reshape([4,2,3])

array([[[36, 38, 52],
        [53, 96, 54]],

       [[97, 44, 89],
        [29, 66, 78]],

       [[55, 75, 19],
        [33, 15, 80]],

       [[99, 86, 82],
        [96, 76, 39]]], dtype=int32)

In [149]:
np.transpose(c)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [155]:
c.reshape([24])

array([36, 38, 52, 53, 96, 54, 97, 44, 89, 29, 66, 78, 55, 75, 19, 33, 15,
       80, 99, 86, 82, 96, 76, 39], dtype=int32)

In [157]:
c.flatten()

array([36, 38, 52, 53, 96, 54, 97, 44, 89, 29, 66, 78, 55, 75, 19, 33, 15,
       80, 99, 86, 82, 96, 76, 39], dtype=int32)

In [158]:
c

array([[[36, 38, 52, 53],
        [96, 54, 97, 44],
        [89, 29, 66, 78]],

       [[55, 75, 19, 33],
        [15, 80, 99, 86],
        [82, 96, 76, 39]]], dtype=int32)

In [163]:
np.where(c==53)

(array([0]), array([0]), array([3]))

In [169]:
c[0][0][3]=100000

In [170]:
c

array([[[    36,     38,     52, 100000],
        [    96,     54,     97,     44],
        [    89,     29,     66,     78]],

       [[    55,     75,     19,     33],
        [    15,     80,     99,     86],
        [    82,     96,     76,     39]]], dtype=int32)

In [171]:
c[0][0][3]=53

In [175]:
c[0,1]

array([96, 54, 97, 44], dtype=int32)

In [173]:
c

array([[[36, 38, 52, 53],
        [96, 54, 97, 44],
        [89, 29, 66, 78]],

       [[55, 75, 19, 33],
        [15, 80, 99, 86],
        [82, 96, 76, 39]]], dtype=int32)